from typing import List, Optional
from fpdf import FPDF
from src.analysis.models import LaboratoryResult
from src.export.exceptions import ReportExportError

class SummaryPDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, "Generated by MediLens AI", align="C")

def _safe_str(text: str) -> str:
    """Safely normalise text for built-in Helvetica (windows-1252), preserving medically relevant symbols."""
    if not text:
        return ""
    # Map common unsupported unicode characters
    replacements = {
        '\u2013': '-', '\u2014': '-', '\u2212': '-', # dashes
        '\u2018': "'", '\u2019': "'", # single quotes
        '\u201c': '"', '\u201d': '"', # double quotes
        '\u00b5': 'u', # micro
        '\u03bc': 'u', # greek mu
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    
    # Finally encode/decode to drop anything else strictly unsupported
    return text.encode('windows-1252', 'replace').decode('windows-1252')

def generate_report_summary_pdf(
    results: List[LaboratoryResult],
    ai_explanation: Optional[str] = None,
) -> bytes:
    if not results:
        raise ReportExportError("Cannot generate a PDF summary without laboratory results.")
        
    pdf = SummaryPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 10, _safe_str("MediLens AI - Medical Report Summary"), align="C")
    pdf.ln(5)
    
    # Subtitle
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, _safe_str("This summary is based only on laboratory values and reference ranges detected in the uploaded report."))
    pdf.ln(5)
    
    # Table
    pdf.set_font("Helvetica", "", 10)
    
    # We use fpdf2 pdf.table() which handles wrapping safely across pages
    with pdf.table(
        col_widths=(60, 25, 25, 40, 40),
        text_align=("LEFT", "RIGHT", "CENTER", "CENTER", "CENTER"),
        line_height=6
    ) as table:
        # Header
        header_row = table.row()
        for header in ["Test", "Value", "Unit", "Reference Range", "Status"]:
            header_row.cell(header, align="CENTER")
            
        # Data
        for r in results:
            row = table.row()
            
            test_name = _safe_str(r.test_name)
            val_str = _safe_str(str(r.value))
            unit_str = _safe_str(r.unit or "")
            
            ref_str = ""
            if r.reference_text:
                ref_str = r.reference_text
            elif r.reference_low is not None and r.reference_high is not None:
                ref_str = f"{r.reference_low} - {r.reference_high}"
            elif r.reference_low is not None:
                ref_str = f"> {r.reference_low}"
            elif r.reference_high is not None:
                ref_str = f"< {r.reference_high}"
            ref_str = _safe_str(ref_str)
            
            status_str = _safe_str(r.status.value)
            
            row.cell(test_name)
            row.cell(val_str)
            row.cell(unit_str)
            row.cell(ref_str)
            row.cell(status_str)
            
    pdf.ln(10)
    
    # AI Explanation
    if ai_explanation and ai_explanation.strip():
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "AI-Generated Plain-Language Explanation", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _safe_str(ai_explanation.strip()))
        pdf.ln(10)
        
    # Disclaimer
    pdf.set_font("Helvetica", "B", 10)
    disclaimer = (
        "This summary is for general educational purposes only. Low, Normal and High labels are "
        "calculated from the reference ranges printed in the uploaded report. This document is not "
        "a diagnosis, treatment plan or substitute for advice from a qualified healthcare professional."
    )
    pdf.multi_cell(0, 6, _safe_str(disclaimer))
    pdf.ln(5)
    
    # Privacy Statement
    pdf.set_font("Helvetica", "I", 10)
    privacy = "The uploaded PDF and extracted report text are not included in this summary."
    pdf.multi_cell(0, 6, _safe_str(privacy))
    
    try:
        return bytes(pdf.output())
    except Exception as e:
        raise ReportExportError("Failed to generate PDF bytes.") from e
